### ISSUE TITLE
issue with .env loading

### ISSUE THREAD

**Issue by ethanj** [nicopauss/pipenv-activate#1]
Hi Nicolas.

I am hopeful pipenv-activate will allow switching away from direnv, but the code seems a little buggy.

On OSX, the following does not work correctly...
https://github.com/Intersec/pipenv-activate/blob/master/pipenv-activate.sh#L15
```
_pipenv_activate_get_pipenv_python() {
    head -n 1 "$(command -v pipenv)" | sed 's/#!//'
}
```

For instance, I use asdf, but even without that active here is the issue:

```
# command -v pipenv
/Library/Frameworks/Python.framework/Versions/3.8/bin/pipenv
```

And with asdf active:
```
# command -v pipenv
/Users/ethan/.asdf/shims/pipenv
```

Not sure how you wanna handle this?

-Ethan

**Comment by nicopauss** [comment]
Thank you for reporting the issue.
I am able to reproduce it.
